In [1]:
import pandas as pd
import numpy as np

data = {
    'ID': [101, 102, 103, 104, 105, 106, 107, 108, 108, 109],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', np.nan, 'Frank', 'Grace', 'Helen', 'Helen', 'Ian'],
    'Age': [25, 30, np.nan, 40, 45, -50, 55, 60, 60, 29],
    'Department': ['HR', 'IT', 'Finance', 'I.T.', 'Hr', 'Finance', 'IT', None, 'HR', 'IT'],
    'Salary': [50000, 60000, 75000, np.nan, 55000, 80000, 62000, 53000, 53000, 70000],
    'Joining Date': ['2020-05-10', '2018-08-15', '2016-09-25', '2017-11-30', '2019-07-01', np.nan, '2015-06-12', '2021-03-15', '2021-03-15', '2014-12-05']
}

df = pd.DataFrame(data)

print(df.head())

    ID     Name   Age Department   Salary Joining Date
0  101    Alice  25.0         HR  50000.0   2020-05-10
1  102      Bob  30.0         IT  60000.0   2018-08-15
2  103  Charlie   NaN    Finance  75000.0   2016-09-25
3  104    David  40.0       I.T.      NaN   2017-11-30
4  105      NaN  45.0         Hr  55000.0   2019-07-01

In [27]:
df

    ID     Name        Age Department   Salary Joining Date
0  101    Alice  25.000000         HR  50000.0   2020-05-10
1  102      Bob  30.000000         IT  60000.0   2018-08-15
2  103  Charlie  32.666667    Finance  75000.0   2016-09-25
3  104    David  40.000000       I.T.  60000.0   2017-11-30
4  105  unknown  45.000000         Hr  55000.0   2019-07-01
5  106    Frank  36.333333    Finance  80000.0   2018-08-15
6  107    Grace  55.000000         IT  62000.0   2015-06-12
7  108    Helen  60.000000         IT  53000.0   2021-03-15
8  108    Helen  60.000000         HR  53000.0   2021-03-15
9  109      Ian  29.000000         IT  70000.0   2014-12-05

In [28]:
# 1.Identify missing values in the dataset.

df.isnull()

      ID   Name    Age  Department  Salary  Joining Date
0  False  False  False       False   False         False
1  False  False  False       False   False         False
2  False  False  False       False   False         False
3  False  False  False       False   False         False
4  False  False  False       False   False         False
5  False  False  False       False   False         False
6  False  False  False       False   False         False
7  False  False  False       False   False         False
8  False  False  False       False   False         False
9  False  False  False       False   False         False

In [29]:
df.isnull().sum()

ID              0
Name            0
Age             0
Department      0
Salary          0
Joining Date    0
dtype: int64

In [30]:
#1.Fill missing values in categorical columns (like "Name" and "Department") with an appropriate value.

df["Name"].fillna("unknown", inplace = True)

df["Department"].fillna("IT", inplace = True)

C:\Users\Rasika\AppData\Local\Temp\ipykernel_21368\1288745190.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Name"].fillna("unknown", inplace = True)
C:\Users\Rasika\AppData\Local\Temp\ipykernel_21368\1288745190.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Department"].fillna("IT", inplace = True)

In [31]:
df

    ID     Name        Age Department   Salary Joining Date
0  101    Alice  25.000000         HR  50000.0   2020-05-10
1  102      Bob  30.000000         IT  60000.0   2018-08-15
2  103  Charlie  32.666667    Finance  75000.0   2016-09-25
3  104    David  40.000000       I.T.  60000.0   2017-11-30
4  105  unknown  45.000000         Hr  55000.0   2019-07-01
5  106    Frank  36.333333    Finance  80000.0   2018-08-15
6  107    Grace  55.000000         IT  62000.0   2015-06-12
7  108    Helen  60.000000         IT  53000.0   2021-03-15
8  108    Helen  60.000000         HR  53000.0   2021-03-15
9  109      Ian  29.000000         IT  70000.0   2014-12-05

In [32]:
#2.Fill missing values in numerical columns (like "Age" and "Salary") using a suitable imputation technique.

df["Age"].fillna(df["Age"].mean(), inplace=True)
df['Salary'].fillna(df['Salary'].median(), inplace=True)

C:\Users\Rasika\AppData\Local\Temp\ipykernel_21368\2617375410.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].median(), inplace=True)

In [33]:
df

    ID     Name        Age Department   Salary Joining Date
0  101    Alice  25.000000         HR  50000.0   2020-05-10
1  102      Bob  30.000000         IT  60000.0   2018-08-15
2  103  Charlie  32.666667    Finance  75000.0   2016-09-25
3  104    David  40.000000       I.T.  60000.0   2017-11-30
4  105  unknown  45.000000         Hr  55000.0   2019-07-01
5  106    Frank  36.333333    Finance  80000.0   2018-08-15
6  107    Grace  55.000000         IT  62000.0   2015-06-12
7  108    Helen  60.000000         IT  53000.0   2021-03-15
8  108    Helen  60.000000         HR  53000.0   2021-03-15
9  109      Ian  29.000000         IT  70000.0   2014-12-05

In [34]:
#4. Identify and remove duplicate records.
df[df.duplicated()]

Empty DataFrame
Columns: [ID, Name, Age, Department, Salary, Joining Date]
Index: []

In [35]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df

    ID     Name        Age Department   Salary Joining Date
0  101    Alice  25.000000         HR  50000.0   2020-05-10
1  102      Bob  30.000000         IT  60000.0   2018-08-15
2  103  Charlie  32.666667    Finance  75000.0   2016-09-25
3  104    David  40.000000       I.T.  60000.0   2017-11-30
4  105  unknown  45.000000         Hr  55000.0   2019-07-01
5  106    Frank -50.000000    Finance  80000.0          NaN
6  107    Grace  55.000000         IT  62000.0   2015-06-12
7  108    Helen  60.000000         IT  53000.0   2021-03-15
8  108    Helen  60.000000         HR  53000.0   2021-03-15
9  109      Ian  29.000000         IT  70000.0   2014-12-05

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [ID, Name, Age, Department, Salary, Joining Date]
Index: []

In [15]:
#5. Convert the "Joining_Date" column to the proper DateTime format.

df.dtypes

ID                int64
Name             object
Age             float64
Department       object
Salary          float64
Joining Date     object
dtype: object

In [16]:
df['Joining Date']

0    2020-05-10
1    2018-08-15
2    2016-09-25
3    2017-11-30
4    2019-07-01
5           NaN
6    2015-06-12
7    2021-03-15
8    2021-03-15
9    2014-12-05
Name: Joining Date, dtype: object

In [17]:
df['Joining Date'] = pd.to_datetime(df['Joining Date'], errors='coerce')

In [18]:
df['Joining Date']

0   2020-05-10
1   2018-08-15
2   2016-09-25
3   2017-11-30
4   2019-07-01
5          NaT
6   2015-06-12
7   2021-03-15
8   2021-03-15
9   2014-12-05
Name: Joining Date, dtype: datetime64[ns]

In [19]:
df[df['Joining Date'].isna()]

    ID   Name   Age Department   Salary Joining Date
5  106  Frank -50.0    Finance  80000.0          NaT

In [20]:
#2. Fill missing values in Joining Date columns with an appropriate value.

df['Joining Date'].fillna(df['Joining Date'].median(), inplace = True)

In [21]:

df['Joining Date']

0   2020-05-10
1   2018-08-15
2   2016-09-25
3   2017-11-30
4   2019-07-01
5   2018-08-15
6   2015-06-12
7   2021-03-15
8   2021-03-15
9   2014-12-05
Name: Joining Date, dtype: datetime64[ns]

In [22]:
#6. Identify any negative values in the "Age" column and replace them with appropriate values.
df["Age"]

0    25.000000
1    30.000000
2    32.666667
3    40.000000
4    45.000000
5   -50.000000
6    55.000000
7    60.000000
8    60.000000
9    29.000000
Name: Age, dtype: float64

In [24]:
df.loc[df['Age'] < 0, 'Age'] = df['Age'].median()

In [25]:
df["Age"]

0    25.000000
1    30.000000
2    32.666667
3    40.000000
4    45.000000
5    36.333333
6    55.000000
7    60.000000
8    60.000000
9    29.000000
Name: Age, dtype: float64

In [37]:
#7. Standardize the department names (e.g., convert variations like "I.T.", "Hr" to a uniform format).

df["Department"]

0         HR
1         IT
2    Finance
3       I.T.
4         Hr
5    Finance
6         IT
7         IT
8         HR
9         IT
Name: Department, dtype: object

In [38]:
df['Department'] = df['Department'].str.upper().str.replace(".", "", regex=False)

In [39]:
df["Department"]

0         HR
1         IT
2    FINANCE
3         IT
4         HR
5    FINANCE
6         IT
7         IT
8         HR
9         IT
Name: Department, dtype: object

In [40]:
#Create a "Salary Category" column (e.g., Low, Medium, High based on salary ranges).

df["Salary"]

0    50000.0
1    60000.0
2    75000.0
3    60000.0
4    55000.0
5    80000.0
6    62000.0
7    53000.0
8    53000.0
9    70000.0
Name: Salary, dtype: float64

In [48]:
def salary_category(salary):
    if pd.isna(salary):
        return "Unknown"
    elif salary < 60000:
        return "Low"
    elif salary < 75000:
        return "Medium"
    else:
        return "High"

In [49]:
df['Salary_Category'] = df['Salary'].apply(salary_category)

In [50]:
df['Salary_Category']

0       Low
1    Medium
2      High
3    Medium
4       Low
5      High
6    Medium
7       Low
8       Low
9    Medium
Name: Salary_Category, dtype: object

In [51]:
df

    ID     Name        Age Department   Salary Joining Date Salary_Category
0  101    Alice  25.000000         HR  50000.0   2020-05-10             Low
1  102      Bob  30.000000         IT  60000.0   2018-08-15          Medium
2  103  Charlie  32.666667    FINANCE  75000.0   2016-09-25            High
3  104    David  40.000000         IT  60000.0   2017-11-30          Medium
4  105  unknown  45.000000         HR  55000.0   2019-07-01             Low
5  106    Frank  36.333333    FINANCE  80000.0   2018-08-15            High
6  107    Grace  55.000000         IT  62000.0   2015-06-12          Medium
7  108    Helen  60.000000         IT  53000.0   2021-03-15             Low
8  108    Helen  60.000000         HR  53000.0   2021-03-15             Low
9  109      Ian  29.000000         IT  70000.0   2014-12-05          Medium

In [52]:
#Rename columns to have consistent naming conventions (e.g., "Joining Date" → "Joining_Date").
df.rename(columns={"Joining Date": "Joining_Date"}, inplace=True)

df.columns = df.columns.str.strip().str.replace(" ", "_")

In [53]:
df.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary', 'Joining_Date',
       'Salary_Category'],
      dtype='object')

In [55]:
#13. Add a Bonus Column and the bonus will be calculated as 10% of the salary for all employees. If an employee has more than 5 years of experience, 
#they get an extra 5% bonus (total 15% of salary).

df['Experience'] = 2025 - df['Joining_Date'].dt.year

In [56]:
df['Experience']

0     5
1     7
2     9
3     8
4     6
5     7
6    10
7     4
8     4
9    11
Name: Experience, dtype: int32

In [57]:
def calculate_bonus(row):
    if row['Experience'] > 5:
        return row['Salary'] * 0.15   # 15%
    else:
        return row['Salary'] * 0.10   # 10%

df['Bonus'] = df.apply(calculate_bonus, axis=1)

In [58]:
df['Bonus']

0     5000.0
1     9000.0
2    11250.0
3     9000.0
4     8250.0
5    12000.0
6     9300.0
7     5300.0
8     5300.0
9    10500.0
Name: Bonus, dtype: float64

In [59]:
df[['Salary', 'Experience', 'Bonus']]

    Salary  Experience    Bonus
0  50000.0           5   5000.0
1  60000.0           7   9000.0
2  75000.0           9  11250.0
3  60000.0           8   9000.0
4  55000.0           6   8250.0
5  80000.0           7  12000.0
6  62000.0          10   9300.0
7  53000.0           4   5300.0
8  53000.0           4   5300.0
9  70000.0          11  10500.0

In [60]:
import numpy as np

df['Bonus'] = np.where(
    df['Experience'] > 5,
    df['Salary'] * 0.15,
    df['Salary'] * 0.10
)

In [61]:
df[['Salary', 'Experience', 'Bonus']]

    Salary  Experience    Bonus
0  50000.0           5   5000.0
1  60000.0           7   9000.0
2  75000.0           9  11250.0
3  60000.0           8   9000.0
4  55000.0           6   8250.0
5  80000.0           7  12000.0
6  62000.0          10   9300.0
7  53000.0           4   5300.0
8  53000.0           4   5300.0
9  70000.0          11  10500.0

In [ ]:
# TASK on DataTime package (Self-study)

#The datetime package in Python is used to work with dates and times, including manipulation, formatting, and arithmetic operations.
It provides classes to work with date, time, and timestamps efficiently.
#import datetime


10. Create new columns for Joining_Year, Joining_Month, and Joining_Day.
11. Calculate a new column "Experience_in_Years" as 2025 - Joining_Year.

In [62]:
df['Joining_Date'] = pd.to_datetime(df['Joining_Date'], errors='coerce')

In [63]:
df['Joining_Year'] = df['Joining_Date'].dt.year
df['Joining_Month'] = df['Joining_Date'].dt.month
df['Joining_Day'] = df['Joining_Date'].dt.day

In [64]:
df['Experience_in_Years'] = 2025 - df['Joining_Year']

In [65]:
df[['Joining_Date', 'Joining_Year', 'Joining_Month', 'Joining_Day', 'Experience_in_Years']]

  Joining_Date  Joining_Year  Joining_Month  Joining_Day  Experience_in_Years
0   2020-05-10          2020              5           10                    5
1   2018-08-15          2018              8           15                    7
2   2016-09-25          2016              9           25                    9
3   2017-11-30          2017             11           30                    8
4   2019-07-01          2019              7            1                    6
5   2018-08-15          2018              8           15                    7
6   2015-06-12          2015              6           12                   10
7   2021-03-15          2021              3           15                    4
8   2021-03-15          2021              3           15                    4
9   2014-12-05          2014             12            5                   11